/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulauno;

import java.util.*;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author renzetti.alessandro
 */
public class FrmGranPremio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGranPremio.class.getName());

    /**
     * Creates new form FrmGranPremio
     */
    public FrmGranPremio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        atxClassifica = new javax.swing.JTextArea();
        btnEventi = new javax.swing.JButton();
        btnAggiungi = new javax.swing.JButton();
        btnBox = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnAvvia = new javax.swing.JButton();
        pbPilota = new javax.swing.JProgressBar();
        pbPilota2 = new javax.swing.JProgressBar();
        pbPilota3 = new javax.swing.JProgressBar();
        pbPilota4 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atxClassifica.setColumns(20);
        atxClassifica.setRows(5);
        jScrollPane1.setViewportView(atxClassifica);

        btnEventi.setText("Eventi");

        btnAggiungi.setText("Aggiungi Pilota");

        btnBox.setText("Box");

        btnStop.setText("Ferma Gara");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnAvvia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Bandiera.png"))); // NOI18N
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pbPilota, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(pbPilota2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbPilota3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pbPilota4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEventi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAvvia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbPilota, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbPilota2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbPilota3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbPilota4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEventi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        // TODO add your handling code here:
        avviaGara();
        btnAvvia.setEnabled(false);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        stopGara();
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGranPremio().setVisible(true));
        SwingUtilities.invokeLater(() -> {
            FrmGranPremio frame = new FrmGranPremio();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxClassifica;
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnBox;
    private javax.swing.JButton btnEventi;
    private javax.swing.JButton btnStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pbPilota;
    private javax.swing.JProgressBar pbPilota2;
    private javax.swing.JProgressBar pbPilota3;
    private javax.swing.JProgressBar pbPilota4;
    // End of variables declaration//GEN-END:variables
    private List<Pilota> piloti;
    private Gara gara;
    private Timer timer;
    boolean tuttiFiniti = true;
    String classifica="";
    
    private void avviaGara() {
        gara = new Gara(100.0);
        gara.aggiungiPilota("Hamilton");
        gara.aggiungiPilota("Verstappen");
        gara.aggiungiPilota("Leclerc");
        gara.aggiungiPilota("Alonso");
        
        piloti = gara.getPiloti();
        
        pbPilota.setValue(0);
        pbPilota2.setValue(0);
        pbPilota3.setValue(0);
        pbPilota4.setValue(0);
        
        gara.avvia();
        
        timer = new Timer(100, e -> aggiorna());
        timer.start();
    }
    
    private void stopGara() {
        if (gara != null) {
            gara.ferma();
            timer.stop();
            btnAvvia.setEnabled(true);
            btnStop.setEnabled(false);
        }
    }
    
    private void aggiornaPB(JProgressBar pb, Pilota pilota) {
        List<Pilota> piloti = gara.getPiloti();
        int percentuale = (int) pilota.getPercentuale();
        pb.setValue(percentuale);
        pb.setString(percentuale + "%");
    }
    
    private void aggiorna() {
        if (gara == null) {
            return;
        }
        if (piloti.size() < 4) {
            return;
        }
        aggiornaPB(pbPilota, piloti.get(0));
        aggiornaPB(pbPilota2, piloti.get(1));
        aggiornaPB(pbPilota3, piloti.get(2));
        aggiornaPB(pbPilota4, piloti.get(3));

        for (Pilota p : piloti) {
            if (p.isInGara()) {
                tuttiFiniti = false;
                break;
            }
        }
        classifica();
        if (tuttiFiniti) {
            timer.stop();
            btnAvvia.setEnabled(true);
            btnStop.setEnabled(false);
        }
    }
        
    public void classifica(){
        // Ordina i piloti per distanza percorsa (dal più avanti al meno avanti)
        List<Pilota> piloti = gara.getPiloti();
        piloti.sort((p1, p2) -> Double.compare(p2.getDistanzaPercorsa(), p1.getDistanzaPercorsa()));
        classifica= "=== CLASSIFICA ===\n\n";
        int posizione = 1;
        for (Pilota p : piloti) {
            classifica += String.format("%d° %s - %.1f%%\n", 
                posizione, 
                p.getNome(), 
                p.getPercentuale());
            posizione++;
        }
        atxClassifica.setText(classifica.toString());   
    }

}
