/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulauno;

import java.awt.Dimension;
import java.awt.Image;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author renzetti.alessandro
 */
public class FrmGranPremio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGranPremio.class.getName());

    /**
     * Creates new form FrmGranPremio
     */
    public FrmGranPremio() {
        initComponents();
        ridimensionaBandiera(150, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxClassifica = new javax.swing.JTextArea();
        btnEventi = new javax.swing.JButton();
        btnAggiungi = new javax.swing.JButton();
        btnBox = new javax.swing.JButton();
        btnRiavvia = new javax.swing.JButton();
        btnAvvia = new javax.swing.JButton();
        pbPilota = new javax.swing.JProgressBar();
        pbPilota2 = new javax.swing.JProgressBar();
        pbPilota3 = new javax.swing.JProgressBar();
        pbPilota4 = new javax.swing.JProgressBar();
        lblCar = new javax.swing.JLabel();
        lblPilota2 = new javax.swing.JLabel();
        lblPilota3 = new javax.swing.JLabel();
        lblPilota4 = new javax.swing.JLabel();
        lblGiriPilota = new javax.swing.JLabel();
        lblGiriPilota2 = new javax.swing.JLabel();
        lblGiriPilota3 = new javax.swing.JLabel();
        lblGiriPilota4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atxClassifica.setColumns(20);
        atxClassifica.setRows(5);
        jScrollPane1.setViewportView(atxClassifica);

        btnEventi.setText("Eventi");

        btnAggiungi.setText("Aggiungi Pilota");

        btnBox.setText("Box");
        btnBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoxActionPerformed(evt);
            }
        });

        btnRiavvia.setText("Riavvia Gara");
        btnRiavvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiavviaActionPerformed(evt);
            }
        });

        btnAvvia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Bandiera.png"))); // NOI18N
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        lblCar.setText("Pilota 1:");

        lblPilota2.setText("Pilota 2:");

        lblPilota3.setText("Pilota 3:");

        lblPilota4.setText("Pilota 4:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPilota2)
                            .addComponent(lblPilota3)
                            .addComponent(lblPilota4)
                            .addComponent(lblCar))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbPilota2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbPilota, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbPilota3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbPilota4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGiriPilota)
                            .addComponent(lblGiriPilota2)
                            .addComponent(lblGiriPilota3)
                            .addComponent(lblGiriPilota4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEventi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRiavvia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(lblCar)
                            .addGap(18, 18, 18)
                            .addComponent(lblPilota2)
                            .addGap(23, 23, 23)
                            .addComponent(lblPilota3)
                            .addGap(23, 23, 23)
                            .addComponent(lblPilota4)
                            .addGap(5, 5, 5))
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbPilota, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiriPilota))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbPilota2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiriPilota2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pbPilota3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiriPilota3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pbPilota4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiriPilota4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEventi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnRiavvia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAvvia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        // TODO add your handling code here:
        avviaGara();
        btnAvvia.setEnabled(false);
        btnRiavvia.setEnabled(true);
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnRiavviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiavviaActionPerformed
        // TODO add your handling code here:
        riavviaGara();
    }//GEN-LAST:event_btnRiavviaActionPerformed

    private void btnBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGranPremio().setVisible(true));
        SwingUtilities.invokeLater(() -> {
            FrmGranPremio frame = new FrmGranPremio();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxClassifica;
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnBox;
    private javax.swing.JButton btnEventi;
    private javax.swing.JButton btnRiavvia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCar;
    private javax.swing.JLabel lblGiriPilota;
    private javax.swing.JLabel lblGiriPilota2;
    private javax.swing.JLabel lblGiriPilota3;
    private javax.swing.JLabel lblGiriPilota4;
    private javax.swing.JLabel lblPilota2;
    private javax.swing.JLabel lblPilota3;
    private javax.swing.JLabel lblPilota4;
    private javax.swing.JProgressBar pbPilota;
    private javax.swing.JProgressBar pbPilota2;
    private javax.swing.JProgressBar pbPilota3;
    private javax.swing.JProgressBar pbPilota4;
    // End of variables declaration//GEN-END:variables
    private List<Pilota> piloti;
    private Gara gara;
    private Timer timer;
    boolean tuttiFiniti = true;
    String classifica="";
    int width = 15;
    int height = 15;
    int numeroGiri = 5;
    double soglia = 100.0 / numeroGiri;
    
    private void avviaGara() {
        int numeroGiri = 10; // default
        
    
        this.numeroGiri = numeroGiri;
        gara = new Gara(100.0);
        gara.aggiungiPilota("Hamilton");
        gara.aggiungiPilota("Verstappen");
        gara.aggiungiPilota("Leclerc");
        gara.aggiungiPilota("Alonso");
        piloti = gara.getPiloti();
        pbPilota.setValue(0);
        pbPilota2.setValue(0);
        pbPilota3.setValue(0);
        pbPilota4.setValue(0);
        gara.avvia();
        timer = new Timer(100, e -> aggiorna());
        timer.start();
        btnAvvia.setEnabled(false);
        btnRiavvia.setEnabled(true);
        lblGiriPilota.setText("Giro 1/" + numeroGiri);
        lblGiriPilota2.setText("Giro 1/" + numeroGiri);        
        lblGiriPilota3.setText("Giro 1/" + numeroGiri);
        lblGiriPilota4.setText("Giro 1/" + numeroGiri);
    }
    
    private void riavviaGara() {
        if (gara != null) {
            gara.ferma();
            timer.stop();
            btnAvvia.setEnabled(true);
            btnRiavvia.setEnabled(false);
        }
    }
    
    private void aggiornaPB(JProgressBar pb, Pilota pilota, JLabel lblGiriPilota1) {
        List<Pilota> piloti = gara.getPiloti();
        int percentuale = (int) pilota.getPercentuale();
        pb.setValue(percentuale);
        pb.setString(percentuale + "%");
        pb.setValue(percentuale);
        
        int giroAttuale = (int) ((pilota.getPercentuale() / 100.0) * numeroGiri) + 1;
        if (giroAttuale > numeroGiri) giroAttuale = numeroGiri;
    
        pb.setString(percentuale + "%");
        lblGiriPilota.setText("Giro " + giroAttuale + "/" + numeroGiri);
        lblGiriPilota2.setText("Giro " + giroAttuale + "/" + numeroGiri);
        lblGiriPilota3.setText("Giro " + giroAttuale + "/" + numeroGiri);
        lblGiriPilota4.setText("Giro " + giroAttuale + "/" + numeroGiri);
        
        /*int progressBarWidth = pb.getWidth();
        int carPosition = (int) ((percentuale / 100.0) * (progressBarWidth - 30));
        lblCar.setBounds(carPosition, 5, 30, 20);*/
    }
    
    private void aggiorna() {
        if (gara == null) {
            return;
        }
        if (piloti.size() < 4) {
            return;
        }
        aggiornaPB(pbPilota,  piloti.get(0), lblGiriPilota);
        lblCar.setText(piloti.get(0).getNome() + ":");
        aggiornaPB(pbPilota2, piloti.get(1), lblGiriPilota2);
        lblPilota2.setText(piloti.get(1).getNome() + ":");
        aggiornaPB(pbPilota3, piloti.get(2), lblGiriPilota3);
        lblPilota3.setText(piloti.get(2).getNome() + ":");
        aggiornaPB(pbPilota4, piloti.get(3), lblGiriPilota4);
        lblPilota4.setText(piloti.get(3).getNome() + ":");

        for (Pilota p : piloti) {
            if (p.isInGara()) {
                tuttiFiniti = false;
                break;
            }
        }
        classifica();
        if (tuttiFiniti) {
            timer.stop();
            btnAvvia.setEnabled(true);
            btnRiavvia.setEnabled(false);
        }
    }
        
    public void classifica(){
        // Ordina i piloti per distanza percorsa (dal più avanti al meno avanti)
        List<Pilota> piloti = gara.getPiloti();
        piloti.sort((p1, p2) -> Double.compare(p2.getDistanzaPercorsa(), p1.getDistanzaPercorsa()));
        classifica= "=== CLASSIFICA ===\n\n";
        int posizione = 1;
        for (Pilota p : piloti) {
            classifica += String.format("%d° %s - %.1f%%\n", 
                posizione, 
                p.getNome(), 
                p.getPercentuale());
            posizione++;
        }
        atxClassifica.setText(classifica.toString());   
    }
    public void ridimensionaBandiera(int width, int height) {
        Image amImg = new ImageIcon(getClass().getResource("/immagini/bandiera.png")).getImage();
        ImageIcon bandiera = new ImageIcon(amImg.getScaledInstance(width, height, Image.SCALE_SMOOTH));
        btnAvvia.setIcon(bandiera); 
    }
    
    public void contaGiri(){
        
    }
}
